FROM php:8.4-fpm

ENV OPCACHE_VALIDATE_TIMESTAMPS=0

ARG MONGODB_VERSION=2.1.4

RUN apt update \
    && apt install -y zlib1g-dev g++ git libicu-dev zip libzip-dev zip libcurl4-openssl-dev pkg-config libssl-dev cron nginx \
    && docker-php-ext-install intl opcache pdo pdo_mysql \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip \
    && pecl install mongodb-${MONGODB_VERSION} \
    && docker-php-ext-enable mongodb \
    && pecl clear-cache \
    && docker-php-ext-enable opcache \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug;

# Use the default production configuration
RUN ln -s "${PHP_INI_DIR}/php.ini-production" "${PHP_INI_DIR}/php.ini" \
    && sed -i "s/^ *memory_limit.*/memory_limit = 512M/g" "${PHP_INI_DIR}/php.ini"

COPY docker/php/conf.d/php-fpm.conf /usr/local/etc/php-fpm.d/www.conf
COPY docker/php/conf.d/tvwatchlist.ini ${PHP_INI_DIR}/conf.d/tvwatchlist.ini

WORKDIR /var/www/html

COPY docker/nginx/conf.d/default.dev.conf /etc/nginx/conf.d/default.conf

ENV COMPOSER_ALLOW_SUPERUSER=1

COPY --from=composer:2.5 /usr/bin/composer /usr/bin/composer

RUN mkdir -p /root/.composer

COPY app /var/www/html
RUN composer install --prefer-dist --no-progress --no-suggest -o --no-interaction --ignore-platform-reqs

COPY cron/crontab /etc/cron.d/tvwatchlist
RUN chmod 0644 /etc/cron.d/tvwatchlist \
    && crontab /etc/cron.d/tvwatchlist

VOLUME /var/www/html

CMD ["php-fpm"]